version: 2.1

jobs:
  build-server-image:
    working_directory: ~/project
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: |
          docker build \
            -t ghcr.io/borchero/meerkat/server:${CIRCLE_TAG} \
            -f build/docker/server.Dockerfile .
      - run: |
          docker tag \
            ghcr.io/borchero/meerkat/server:${CIRCLE_TAG} \
            ghcr.io/borchero/meerkat/server:latest
      - run: docker push ghcr.io/borchero/meerkat/server:${CIRCLE_TAG}
      - run: docker push ghcr.io/borchero/meerkat/server:latest

  build-operator-image:
    working_directory: ~/project
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: |
          docker build \
            -t ghcr.io/borchero/meerkat/operator:${CIRCLE_TAG} \
            -f build/docker/operator.Dockerfile .
      - run: |
          docker tag \
            ghcr.io/borchero/meerkat/operator:${CIRCLE_TAG} \
            ghcr.io/borchero/meerkat/operator:latest
      - run: docker push ghcr.io/borchero/meerkat/operator:${CIRCLE_TAG}
      - run: docker push ghcr.io/borchero/meerkat/operator:latest

  upload-chart:
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - run: |
          apk add --no-cache gettext

          cd ..
          git clone git@github.com:borchero/helm-charts.git

          export DST=helm-charts/charts/meerkat-operator@${CIRCLE_TAG}
          mv project/deploy/chart ${DST}

          envsubst < ${DST}/values.yaml > ${DST}/values.subst.yaml
          mv ${DST}/values.subst.yaml ${DST}/values.yaml

          envsubst < ${DST}/Chart.yaml > ${DST}/Chart.subst.yaml
          mv ${DST}/Chart.subst.yaml ${DST}/Chart.yaml

          cd helm-charts
          git config user.name "circleci"
          git config user.email "noreply@borchero.com"
          git add .
          git commit -m "Update Charts"
          git push origin master

workflows:
  version: 2
  deploy:
    jobs:
      - build-server-image
      - build-operator-image
      - upload-chart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
