apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccount.name" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-binding

subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-binding

subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccount.name" . }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-leader
